### ISSUE TITLE
Document how to implement more commands

### ISSUE THREAD

**Issue by probonopd** [klauweg/vitalk#1]
I would like to use this with a Vitotronic 200 KW 2. Currently I am using vcontrold but its libxml2 dependency adds a lot of overhead to small embedded systems like routers running OpenWrt. Hence I am looking for something more lightweight and found ViTalk.

Please document how I can use the vcontrold XML files to get the needed commands into ViTalk. Ideally ViTalk could take a vcontrold XML file at **compile time** and use the information therein to generate a binary supporting all commands contained in the XML.

**Comment by klauweg** [comment]
> I would like to use this with a Vitotronic 200 KW 2. Currently I am using vcontrold but its libxml2 dependency adds a lot of overhead to small embedded systems like routers running OpenWrt. Hence I am looking for something more lightweight and found ViTalk.

Exactly this was the motivation for me to write ViTalk. You can use it
even on small 8-bit AVR mcus or something like that.

> Please document how I can use the vcontrold XML files to get the needed commands into ViTalk. Ideally ViTalk could take a vcontrold XML file at **compile time** and use the information therein to generate a binary supporting all commands contained in the XML.

Unfortunately (?) this is not possible. You should have a look at
vito_parameter.c There is a really small C-function for every used
parameter to perform the needed conversions. Sometimes only two lines,
sometimes more like reading the error log.
The coresponding address is defined there also.
